name: Metrics

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          template: repository
          filename: metrics.repository2.svg
          token: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}
          user: mcrewcow
          repo: RGC_Dnmt3a_pONC2d_paper
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes
